### ISSUE TITLE
How to read (not write) the communication with HT1661B

### ISSUE THREAD

**Issue by pmsalvino** [5N44P/ht1621-7-seg#14]
Hi! It’s been a while I’ve been looking for a code in which I could “intercept” (using NodeMCU) the communication between the Main Board and the display board of my Water Heater. So far I’ve been able to copy the most important features of physical LED display but not the information. Exemple: I manage to turn the water heater’s display using Blying app but not displaying temperature and heating level. How hard would be to adapt the code to write the HT1661B to intercept and read CS, Clock and so pins?

**Comment by valerionew** [comment]
Hi. Sorry but this is not really relevant to this library! You are even talking about a different driver
