### ISSUE TITLE
Display battery level without battery icon

### ISSUE THREAD

**Issue by iansan5653** [5N44P/ht1621-7-seg#17]
The three bars on the right side of the display could be useful for many applications outside of simply displaying battery level. For example, you might display GPS fix confidence based on the number of satellites, or you could indicate whether a value is rising or falling. But the `setBatteryLevel` function forces the 🔋 icon to display, so it can be confusing to use it for anything else.

If we could call `setBatteryLevel(2, false)` to disable the battery icon, this would be much more useful.

I took a look at the code but I am really not sure how to tackle this or if the LCD even supports it at all.

**Comment by valerionew** [comment]
Unfortunately on my version of the LCD the battery symbol is part of the last segment if i remember correctly.

**Comment by valerionew** [comment]
Anyways I'll have to check this

**Comment by valerionew** [comment]
Yes they're the same segment, sorry!

**Comment by iansan5653** [comment]
Makes sense, thanks!
