### ISSUE TITLE
Debug "serial prints"

### ISSUE THREAD

**Issue by fulda1** [5N44P/ht1621-7-seg#18]
In code remain some debug outputs, that utilize (and reset) Serial library.
It is sad in case you use serial port for other reason.

In file:
ht1621-7-seg/tree/master/src)/HT1621.cpp
lines 201, 202, 203, 209 and 216

**Comment by valerionew** [comment]
Thank you, that was an easy fix. The new version of the library will be distributed via Arduino soon

**Comment by fulda1** [comment]
I created pull request #19 to make it more easy :)

**Comment by valerionew** [comment]
Thanks, i did not understand that you were going to fix it. It is already fixed now, but thank you anyways!

**Comment by fulda1** [comment]
You are quicker than me :)
