### ISSUE TITLE
ATSAMD21G18

### ISSUE THREAD

**Issue by furieuxjk** [5N44P/ht1621-7-seg#2]
Does this library work with ATSAMD21G18 MCU?

**Comment by valerionew** [comment]
Since it's using wiring's hardware abstraction layer, it should work with every Arduino board. 
At the moment i don't have any MKR board on hand to test it. If you can, test it and let me know

**Comment by furieuxjk** [comment]
Well I also don't have this MCU to test yet, but when I will have it, I can update this issue.

**Comment by valerionew** [comment]
Thank you, keep me updated!

**Comment by furieuxjk** [comment]
I confirm that this library works with ATSAMD21G18 MCU.

I tested standalone ATSAMD21G18A-AU chip with HT1621 LCD controller, but I used different LCD. So for now I just need to map correct segments for my particular LCD, but I think it will work with LCD used in your library.

Thanks!

**Comment by valerionew** [comment]
Can we add support for your version of lcd? Does it have a model number? Do you have a link?
