### ISSUE TITLE
display don't work on esp32

### ISSUE THREAD

**Issue by didi110296** [5N44P/ht1621-7-seg#3]
Hello, i'm trying to connect an ht1621 display to esp32 but that don't work, just the led is on, i've tried to change pins many times but nothing.
I think this library is no compatible?

Thanks.

**Comment by valerionew** [comment]
The library is not compatible yet with faster processors. 
A fix will probabily come in 2.1.0

**Comment by didi110296** [comment]
Ok thank you :)

**Comment by valerionew** [comment]
This fork contains a fix: 
https://github.com/JarekParal/ht1621-7-seg

**Comment by didi110296** [comment]
Ok nice

**Comment by valerionew** [comment]
@didi110296 would you test the [new branch](https://github.com/5N44P/ht1621-7-seg/tree/faster-processors-fixes)?

**Comment by didi110296** [comment]
i've tried, that work fine

**Comment by valerionew** [comment]
Thank you!
