### ISSUE TITLE
Backlight control does not work.

### ISSUE THREAD

**Issue by Erfeniuses** [5N44P/ht1621-7-seg#6]
Using OPEN-SMART "LCD Module 2.4 inch 6-Digit 7 Segment LCD Display Module HT1621" from aliexpress and the code works great.

Somehow the LED+ pin does not act when it gets pulled down / hi.  PCB ver 5.1
There is is S1 jumper on the board that is open by default, preventing the LED+ state to flow to Driver chip.

Has anyone have any idea how to make the backligth control work? This is HW issue.

**Comment by valerionew** [comment]
Can you post a picture of the back of your module's pcb?

**Comment by Erfeniuses** [comment]
![Open-smart-HT1621-LCD](https://user-images.githubusercontent.com/20818646/65971641-27b32500-e471-11e9-9842-45b2cdf3a538.jpg)

**Comment by Erfeniuses** [comment]
https://www.aliexpress.com/item/32677947011.html?spm=a2g0o.cart.0.0.7b273c00yFaCro&mp=1

**Comment by Erfeniuses** [comment]
This is such b*****..  S1 is the toogle for PIN LED+ or forceFeed for 5V.
So, connecting lower pad (open by default) and disconnecting the upper pad (connected by default).

NOW IT WORKS!
thank you!! close the issue!

**Comment by valerionew** [comment]
I was about to say the same thing, glad you figured it out

**Comment by fpilee** [comment]
Hi, do you need to wire these two pins to have the light control?
